services:
  postgres:
    container_name: postgres_repsy
    image: postgres
    environment:
      POSTGRES_USER: baser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repsy
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_repsy
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  repsy-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: baser/repsy-api:latest
    container_name: repsy-api
    ports:
      - "8222:8222"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
      - spring
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    depends_on:
      postgres:
        condition: service_started

  minio:
    container_name: minio-repsy
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Admin paneli için
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - spring
    restart: unless-stopped

networks:
  postgres:
    name: postgres
    driver: bridge
  spring:
    name: spring
    driver: bridge

volumes:
  postgres:
  pgadmin:
  minio-data: